option("modules")
    set_default(false)
    set_showmenu(true)
    set_description("Enable c++20 stl header units (default: false)")
option_end()

option("test")
    set_default(false)
    set_showmenu(true)
    set_description("Enable test (default: false)")
option_end()
