option("modules")
    set_default(false)
    set_showmenu(true)
    set_description("Enable c++20 stl header units (default: false)")
option_end()

option("test")
    set_default(false)
    set_showmenu(true)
    set_description("Enable test (default: false)")
option_end()

option("volk")
    set_default(false)
    set_showmenu(true)
    set_description("Using volk to improve vulkan performance (default: false)")
    add_defines("USE_VOLK", "VK_NO_PROTOTYPES")
option_end()
